### ISSUE TITLE
Access not granted or expired.

### ISSUE THREAD

**Issue by iscmauricio** [googleworkspace/apps-script-oauth2#270] opened 2021-03-02 22:53 UTC
I am using you library to do an oauth2 workflow, everything works well but after a few seconds (random time) or minutes the complement seems to forguet the access token that our API authroized and appears the error:

Error: Access not granted or expired. (línea 454).

We are using:

``
 // Set the property store where authorized tokens should be persisted.       
.setPropertyStore(PropertiesService.getUserProperties())
``

The flow is: User clic on complement, send to base login url, authorize app, script (webapp) changes the authorization for the access token, then the script has the access token. If i close the document the token lossees and some times just stop working. Seems that **PropertiesService.getUserProperties()** cannot save the token or something like.

As your docs says, but seems it doesnt work.

Thank you.

**Comment by erickoledadevrel** [comment] 2021-03-03 00:44
Sorry to hear you are having trouble. I'm not sure where the problem is, and unfortunately you didn't give quite enough information to narrow it down. Which API are you authorizing against? Some APIs have very strange rules around token expiration which could be a factor. You should do some more debugging to see what is being stored in the user properties and if it looks valid.

I'd also suggest adding a cache to your service as well. The properties store can be a little slow to replicate, and so you may be hitting another instance of the server that isn't aware of the new token.

**Comment by iscmauricio** [comment] 2021-03-03 16:25
We are connecting to our API. The access token has a expire policy of days. We are not using cache as you suggest, but will try.
Will debug user properties and give you a feedback.

**Comment by erickoledadevrel** [comment] 2021-03-15 23:41
Thanks for closing the loop on this. As per [the spec](https://tools.ietf.org/html/rfc6749#section-5.1), `expires_in` should be in seconds. That said, many APIs don't follow spec exactly. If you want to have native support for this API you could a method `setExpiryUnits()` that takes an enum specifying either seconds or days. I'd happily accept a PR.

**Closed by erickoledadevrel** 2021-03-15 23:41 UTC
